# Generated by Django 4.0 on 2023-03-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCareers', models.CharField(max_length=50, verbose_name='nameCareers')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'careers',
                'verbose_name_plural': 'careers',
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='emergency_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_name', models.CharField(max_length=100, verbose_name='emergency_name phone')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='emergency phone')),
                ('emergency_phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency phone 2')),
                ('blood_type', models.CharField(max_length=10, verbose_name='blood type')),
                ('status', models.CharField(choices=[('en uso', 'En Uso'), ('eliminado', 'Eliminado')], default='en uso', max_length=10, verbose_name='status')),
                ('allergy', models.CharField(max_length=100, verbose_name='allergy')),
                ('allergy2', models.CharField(blank=True, max_length=100, null=True, verbose_name='allergy 2')),
            ],
            options={
                'verbose_name': 'emergency_info',
                'verbose_name_plural': 'emergency_infos',
                'db_table': 'emergency_info',
            },
        ),
        migrations.CreateModel(
            name='request_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='reason')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'request_reason',
                'verbose_name_plural': 'request_reasons',
                'db_table': 'request_reason',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalName', models.CharField(max_length=100, verbose_name='personalName')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('license', models.CharField(max_length=20, verbose_name='license')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('grade', models.CharField(choices=[('ninguno', 'Ninguno'), ('10a', '10A'), ('10b', '10B'), ('9a', '9A'), ('9b', '9B'), ('8a', '8A'), ('8b', '8B'), ('7a', '7A'), ('7b', '7B'), ('6a', '6A'), ('6b', '6B'), ('5a', '5A'), ('5b', '5B'), ('4a', '4A'), ('4b', '4B'), ('3a', '3A'), ('3b', '3B'), ('2a', '2A'), ('2b', '2B'), ('1a', '1A'), ('1b', '1B')], default='ninguno', max_length=10, verbose_name='grade')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('status', models.CharField(choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('inactivo', 'Inactivo')], default='estudiante', max_length=15, verbose_name='status')),
                ('photo', models.ImageField(blank=True, default='alumn/logouni.jpg', null=True, upload_to='alumn/photo', verbose_name='photo')),
                ('id_careers', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credential.careers', verbose_name='careers')),
                ('id_emInfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credential.emergency_info', verbose_name='emergency_info')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'student',
            },
        ),
    ]
