# Generated by Django 4.0 on 2023-03-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='request_reason',
            name='id_st',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credential.student', verbose_name='student'),
        ),
    ]
