# Generated by Django 4.0 on 2023-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_info',
            name='emergency_name',
            field=models.CharField(max_length=100, verbose_name='emergency_name'),
        ),
    ]
