# Generated by Django 4.0 on 2023-03-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_alter_emergency_info_emergency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_reason',
            name='status',
            field=models.CharField(choices=[('revision', 'Revision'), ('denegada', 'Denegada'), ('aceptado', 'Aceptado'), ('eliminado', 'Eliminado')], default='activa', max_length=10, verbose_name='status'),
        ),
    ]
